baseURL = "https://www.mildlyskilled.com/"
languageCode = "en-gb"
title = "Mildly Skilled"
theme = "hugo-future-imperfect"
publishDir = "public"
relativeUrls = true
googleAnalytics = "UA-121895834-1"
enableRobotsTXT = true
canonifyURLs = true
socialShare          = true
socialShareTwitter   = true
socialShareGoogleplus = false
socialShareFacebook  = true
socialShareReddit    = true
socialShareLinkedin  = true
socialShareStumbleupon = false
socialSharePinterest = false
socialShareEmail     = false

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  description = "Software development for the mildly skilled. A blog maintained by me Kwabena Aning, suffice it to say these are my opinions and I share them freely with the understanding that you acknowledge that they are my own."
  author = "Kwabena Aning"
  navbarTitle = "Mildly Skilled"
  paginate = 10
  footnotereturnlinkcontents = "↩"
  avatar = "images/avatar.jpeg"
  gravatar = "kwabena.aning@gmail.com"
  disable_mathjax = true
  date_format = "Mon, 02 January 2006"
  mainSections = ["posts"]
  includeReadingTime = true

[[params.menu]]
  before = true
  label = "Home"
  link = "/"

[[params.menu]]
    before = false
    label = "About"
    link = "about/"

[[params.menu]]
  before = false
  label = "Tags"
  link = "tags/"

  # Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  identifier = "fa fa-sitemap"
  weight = 4


[params.profile]
  follow_button = "https://github.com/mildlyskilled"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true

[params.intro]
  header    = ""
  paragraph = "Software engineering for the mildly skilled"
  about     = "Software development for the mildly skilled. A blog maintained by me Kwabena Aning, suffice it to say these are my opinions and I share them freely with the understanding that you acknowledge that they are my own."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "images/avatar.jpeg"
    # Sets Image to be a cirlce
    circle    = true
    # Sets Image to be Future Imperfect's hexagon
    width     = ""
    alt       = "Kwabena Aning"


[social]
  github = "mildlyskilled"
  instagram = "mildlyskilled"
  linkedin = "kaning"
  twitter = "KwabenaAning"
